[package]
name = "bevy-rusty-rust-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_rapier3d = { version = "0.26.0", features = [ "simd-stable", "debug-render-3d" ] }
rand = "0.8.5"

